invisibility:
  cost: 5.0        # Cost of using the invisibility spell (in Ducaten)
  duration: 6000     # Duration of invisibility in ticks 6000 Ticks is 1 minuut
  cooldown: 12000   # Cooldown duration in ticks after invisibility expires

messages:
  insufficient_funds: "You do not have enough money to use this ability!"
  invisibility_activate: "You are now invisible for %duration% seconds!"
  invisibility_expired: "Your invisibility has expired."
  invisibility_cancelled: "Your invisibility has been cancelled."
  cooldown_active: "You must wait %time% more minutes before using this again."
