invisibility:
  cost: 5.0        # Cost of using the invisibility spell (in currency)
  duration: 600     # Duration of invisibility in ticks (1 tick = 1/20 second)
  cooldown: 600     # Cooldown duration in ticks after invisibility expires

messages:
  insufficient_funds: "You do not have enough money to use this ability!"
  invisibility_activate: "You are now invisible for %duration% seconds!"
  invisibility_expired: "Your invisibility has expired."
  invisibility_cancelled: "Your invisibility has been cancelled."
  cooldown_active: "You must wait %time% more minutes before using this again."
